create extension if not exists "postgis" with schema "extensions";

create table "public"."Bid" (
	"id" bigint generated by default as identity not null,
	"created_at" timestamp with time zone not null default now(),
	"owner" uuid not null,
	"work_start_date" date not null,
	"work_end_date" date not null,
	"work_package" bigint not null
);

-- alter table
-- 	"public"."Bid" enable row level security;

create table "public"."Issue" (
	"id" bigint generated by default as identity not null,
	"created_at" timestamp with time zone not null default now(),
	"updated_at" timestamp with time zone,
	"status" bigint not null default '1' :: bigint,
	"created_user" uuid,
	"work_package" bigint
);

-- alter table
-- 	"public"."Issue" enable row level security;

create table "public"."IssueStatus" (
	"id" bigint generated by default as identity not null,
	"created_at" timestamp with time zone not null default now(),
	"display_name" character varying not null
);

-- alter table
-- 	"public"."IssueStatus" enable row level security;

create table "public"."WorkDetail" (
	"id" bigint generated by default as identity not null,
	"created_at" timestamp with time zone not null default now(),
	"issue" bigint not null,
	"added_by" uuid not null
);

-- alter table
-- 	"public"."WorkDetail" enable row level security;

create table "public"."WorkPackage" (
	"id" bigint generated by default as identity not null,
	"created_at" timestamp with time zone not null default now(),
	"display_name" character varying not null,
	"quote_due_date" timestamp with time zone not null,
	"status" bigint
);

-- alter table
-- 	"public"."WorkPackage" enable row level security;

create table "public"."WorkPackageStatus" (
	"id" bigint generated by default as identity not null,
	"created_at" timestamp with time zone not null default now(),
	"display_name" character varying not null
);

-- alter table
-- 	"public"."WorkPackageStatus" enable row level security;

CREATE UNIQUE INDEX "Bid_pkey" ON public."Bid" USING btree (id);

CREATE UNIQUE INDEX "IssueStatus_display_name_key" ON public."IssueStatus" USING btree (display_name);

CREATE UNIQUE INDEX "IssueStatus_pkey" ON public."IssueStatus" USING btree (id);

CREATE UNIQUE INDEX "Issue_pkey" ON public."Issue" USING btree (id);

CREATE UNIQUE INDEX "WorkDetail_pkey" ON public."WorkDetail" USING btree (id);

CREATE UNIQUE INDEX "WorkPackageStatus_pkey" ON public."WorkPackageStatus" USING btree (id);

CREATE UNIQUE INDEX "WorkPackage_pkey" ON public."WorkPackage" USING btree (id);

alter table
	"public"."Bid"
add
	constraint "Bid_pkey" PRIMARY KEY using index "Bid_pkey";

alter table
	"public"."Issue"
add
	constraint "Issue_pkey" PRIMARY KEY using index "Issue_pkey";

alter table
	"public"."IssueStatus"
add
	constraint "IssueStatus_pkey" PRIMARY KEY using index "IssueStatus_pkey";

alter table
	"public"."WorkDetail"
add
	constraint "WorkDetail_pkey" PRIMARY KEY using index "WorkDetail_pkey";

alter table
	"public"."WorkPackage"
add
	constraint "WorkPackage_pkey" PRIMARY KEY using index "WorkPackage_pkey";

alter table
	"public"."WorkPackageStatus"
add
	constraint "WorkPackageStatus_pkey" PRIMARY KEY using index "WorkPackageStatus_pkey";

alter table
	"public"."Bid"
add
	constraint "Bid_owner_fkey" FOREIGN KEY (owner) REFERENCES public.civic_os_users(id) not valid;

alter table
	"public"."Bid" validate constraint "Bid_owner_fkey";

alter table
	"public"."Bid"
add
	constraint "Bid_work_package_fkey" FOREIGN KEY (work_package) REFERENCES "WorkPackage"(id) not valid;

alter table
	"public"."Bid" validate constraint "Bid_work_package_fkey";

alter table
	"public"."Issue"
add
	constraint "Issue_created_user_fkey" FOREIGN KEY (created_user) REFERENCES public.civic_os_users(id) not valid;

alter table
	"public"."Issue" validate constraint "Issue_created_user_fkey";

alter table
	"public"."Issue"
add
	constraint "Issue_status_fkey" FOREIGN KEY (status) REFERENCES "IssueStatus"(id) not valid;

alter table
	"public"."Issue" validate constraint "Issue_status_fkey";

alter table
	"public"."Issue"
add
	constraint "Issue_work_package_fkey" FOREIGN KEY (work_package) REFERENCES "WorkPackage"(id) not valid;

alter table
	"public"."Issue" validate constraint "Issue_work_package_fkey";

alter table
	"public"."IssueStatus"
add
	constraint "IssueStatus_display_name_key" UNIQUE using index "IssueStatus_display_name_key";

alter table
	"public"."WorkDetail"
add
	constraint "WorkDetail_added_by_fkey" FOREIGN KEY (added_by) REFERENCES public.civic_os_users(id) not valid;

alter table
	"public"."WorkDetail" validate constraint "WorkDetail_added_by_fkey";

alter table
	"public"."WorkDetail"
add
	constraint "WorkDetail_issue_fkey" FOREIGN KEY (issue) REFERENCES "Issue"(id) not valid;

alter table
	"public"."WorkDetail" validate constraint "WorkDetail_issue_fkey";

alter table
	"public"."WorkPackage"
add
	constraint "WorkPackage_status_fkey" FOREIGN KEY (status) REFERENCES "WorkPackageStatus"(id) not valid;

alter table
	"public"."WorkPackage" validate constraint "WorkPackage_status_fkey";

grant delete on table "public"."Bid" to "web_anon";

grant
insert
	on table "public"."Bid" to "web_anon";

grant references on table "public"."Bid" to "web_anon";

grant
select
	on table "public"."Bid" to "web_anon";

grant trigger on table "public"."Bid" to "web_anon";

grant truncate on table "public"."Bid" to "web_anon";

grant
update
	on table "public"."Bid" to "web_anon";

grant delete on table "public"."Bid" to "authenticated";

grant
insert
	on table "public"."Bid" to "authenticated";

grant references on table "public"."Bid" to "authenticated";

grant
select
	on table "public"."Bid" to "authenticated";

grant trigger on table "public"."Bid" to "authenticated";

grant truncate on table "public"."Bid" to "authenticated";

grant
update
	on table "public"."Bid" to "authenticated";

grant delete on table "public"."Issue" to "web_anon";

grant
insert
	on table "public"."Issue" to "web_anon";

grant references on table "public"."Issue" to "web_anon";

grant
select
	on table "public"."Issue" to "web_anon";

grant trigger on table "public"."Issue" to "web_anon";

grant truncate on table "public"."Issue" to "web_anon";

grant
update
	on table "public"."Issue" to "web_anon";

grant delete on table "public"."Issue" to "authenticated";

grant
insert
	on table "public"."Issue" to "authenticated";

grant references on table "public"."Issue" to "authenticated";

grant
select
	on table "public"."Issue" to "authenticated";

grant trigger on table "public"."Issue" to "authenticated";

grant truncate on table "public"."Issue" to "authenticated";

grant
update
	on table "public"."Issue" to "authenticated";

grant delete on table "public"."IssueStatus" to "web_anon";

grant
insert
	on table "public"."IssueStatus" to "web_anon";

grant references on table "public"."IssueStatus" to "web_anon";

grant
select
	on table "public"."IssueStatus" to "web_anon";

grant trigger on table "public"."IssueStatus" to "web_anon";

grant truncate on table "public"."IssueStatus" to "web_anon";

grant
update
	on table "public"."IssueStatus" to "web_anon";

grant delete on table "public"."IssueStatus" to "authenticated";

grant
insert
	on table "public"."IssueStatus" to "authenticated";

grant references on table "public"."IssueStatus" to "authenticated";

grant
select
	on table "public"."IssueStatus" to "authenticated";

grant trigger on table "public"."IssueStatus" to "authenticated";

grant truncate on table "public"."IssueStatus" to "authenticated";

grant
update
	on table "public"."IssueStatus" to "authenticated";

grant delete on table "public"."IssueStatus" to "authenticated";

grant
insert
	on table "public"."IssueStatus" to "authenticated";

grant references on table "public"."IssueStatus" to "authenticated";

grant
select
	on table "public"."IssueStatus" to "authenticated";

grant trigger on table "public"."IssueStatus" to "authenticated";

grant truncate on table "public"."IssueStatus" to "authenticated";

grant
update
	on table "public"."IssueStatus" to "authenticated";

grant delete on table "public"."WorkDetail" to "web_anon";

grant
insert
	on table "public"."WorkDetail" to "web_anon";

grant references on table "public"."WorkDetail" to "web_anon";

grant
select
	on table "public"."WorkDetail" to "web_anon";

grant trigger on table "public"."WorkDetail" to "web_anon";

grant truncate on table "public"."WorkDetail" to "web_anon";

grant
update
	on table "public"."WorkDetail" to "web_anon";

grant delete on table "public"."WorkDetail" to "authenticated";

grant
insert
	on table "public"."WorkDetail" to "authenticated";

grant references on table "public"."WorkDetail" to "authenticated";

grant
select
	on table "public"."WorkDetail" to "authenticated";

grant trigger on table "public"."WorkDetail" to "authenticated";

grant truncate on table "public"."WorkDetail" to "authenticated";

grant
update
	on table "public"."WorkDetail" to "authenticated";

grant delete on table "public"."WorkDetail" to "authenticated";

grant
insert
	on table "public"."WorkDetail" to "authenticated";

grant references on table "public"."WorkDetail" to "authenticated";

grant
select
	on table "public"."WorkDetail" to "authenticated";

grant trigger on table "public"."WorkDetail" to "authenticated";

grant truncate on table "public"."WorkDetail" to "authenticated";

grant
update
	on table "public"."WorkDetail" to "authenticated";

grant delete on table "public"."WorkPackage" to "web_anon";

grant
insert
	on table "public"."WorkPackage" to "web_anon";

grant references on table "public"."WorkPackage" to "web_anon";

grant
select
	on table "public"."WorkPackage" to "web_anon";

grant trigger on table "public"."WorkPackage" to "web_anon";

grant truncate on table "public"."WorkPackage" to "web_anon";

grant
update
	on table "public"."WorkPackage" to "web_anon";

grant delete on table "public"."WorkPackage" to "authenticated";

grant
insert
	on table "public"."WorkPackage" to "authenticated";

grant references on table "public"."WorkPackage" to "authenticated";

grant
select
	on table "public"."WorkPackage" to "authenticated";

grant trigger on table "public"."WorkPackage" to "authenticated";

grant truncate on table "public"."WorkPackage" to "authenticated";

grant
update
	on table "public"."WorkPackage" to "authenticated";

grant delete on table "public"."WorkPackage" to "authenticated";

grant
insert
	on table "public"."WorkPackage" to "authenticated";

grant references on table "public"."WorkPackage" to "authenticated";

grant
select
	on table "public"."WorkPackage" to "authenticated";

grant trigger on table "public"."WorkPackage" to "authenticated";

grant truncate on table "public"."WorkPackage" to "authenticated";

grant
update
	on table "public"."WorkPackage" to "authenticated";

grant delete on table "public"."WorkPackageStatus" to "web_anon";

grant
insert
	on table "public"."WorkPackageStatus" to "web_anon";

grant references on table "public"."WorkPackageStatus" to "web_anon";

grant
select
	on table "public"."WorkPackageStatus" to "web_anon";

grant trigger on table "public"."WorkPackageStatus" to "web_anon";

grant truncate on table "public"."WorkPackageStatus" to "web_anon";

grant
update
	on table "public"."WorkPackageStatus" to "web_anon";

grant delete on table "public"."WorkPackageStatus" to "authenticated";

grant
insert
	on table "public"."WorkPackageStatus" to "authenticated";

grant references on table "public"."WorkPackageStatus" to "authenticated";

grant
select
	on table "public"."WorkPackageStatus" to "authenticated";

grant trigger on table "public"."WorkPackageStatus" to "authenticated";

grant truncate on table "public"."WorkPackageStatus" to "authenticated";

grant
update
	on table "public"."WorkPackageStatus" to "authenticated";

grant delete on table "public"."WorkPackageStatus" to "authenticated";

grant
insert
	on table "public"."WorkPackageStatus" to "authenticated";

grant references on table "public"."WorkPackageStatus" to "authenticated";

grant
select
	on table "public"."WorkPackageStatus" to "authenticated";

grant trigger on table "public"."WorkPackageStatus" to "authenticated";

grant truncate on table "public"."WorkPackageStatus" to "authenticated";

grant
update
	on table "public"."WorkPackageStatus" to "authenticated";

create policy "Enable read access for all users" on "public"."Bid" as permissive for
select
	to public using (true);

create policy "Enable read access for all users" on "public"."Issue" as permissive for
select
	to public using (true);

create policy "Enable read access for all users" on "public"."IssueStatus" as permissive for
select
	to public using (true);

create policy "Enable read access for all users" on "public"."WorkDetail" as permissive for
select
	to public using (true);

create policy "Enable read access for all users" on "public"."WorkPackage" as permissive for
select
	to public using (true);

create policy "Enable read access for all users" on "public"."WorkPackageStatus" as permissive for
select
	to public using (true);

-- Auto-update triggers for updated_at
CREATE TRIGGER update_issue_updated_at
  BEFORE UPDATE ON public."Issue"
  FOR EACH ROW
  EXECUTE FUNCTION public.update_updated_at_column();

CREATE TRIGGER update_work_package_updated_at
  BEFORE UPDATE ON public."WorkPackage"
  FOR EACH ROW
  EXECUTE FUNCTION public.update_updated_at_column();

NOTIFY pgrst,
'reload schema';