-- =====================================================
-- Example Application: Pot Hole Observation System
-- =====================================================

-- Enable PostGIS extension (installed in public schema by default)
CREATE EXTENSION IF NOT EXISTS postgis;

-- Bid table
CREATE TABLE "public"."Bid" (
	"id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
	"display_name" TEXT NOT NULL,
	"owner" UUID NOT NULL,
	"work_start_date" DATE NOT NULL,
	"work_end_date" DATE NOT NULL,
	"work_package" BIGINT NOT NULL
);

-- Issue table
CREATE TABLE "public"."Issue" (
	"id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
	"updated_at" TIMESTAMP WITH TIME ZONE,
	"display_name" TEXT NOT NULL,
	"status" BIGINT NOT NULL DEFAULT '1'::BIGINT,
	"created_user" UUID,
	"work_package" BIGINT
);

-- IssueStatus table
CREATE TABLE "public"."IssueStatus" (
	"id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
	"display_name" CHARACTER VARYING NOT NULL
);

-- WorkDetail table
CREATE TABLE "public"."WorkDetail" (
	"id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
	"display_name" TEXT NOT NULL,
	"issue" BIGINT NOT NULL,
	"added_by" UUID NOT NULL
);

-- WorkPackage table
CREATE TABLE "public"."WorkPackage" (
	"id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
	"display_name" CHARACTER VARYING NOT NULL,
	"quote_due_date" TIMESTAMP WITH TIME ZONE NOT NULL,
	"status" BIGINT
);

-- WorkPackageStatus table
CREATE TABLE "public"."WorkPackageStatus" (
	"id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
	"display_name" CHARACTER VARYING NOT NULL
);

-- Create indexes
CREATE UNIQUE INDEX "Bid_pkey" ON public."Bid" USING btree (id);
CREATE UNIQUE INDEX "IssueStatus_display_name_key" ON public."IssueStatus" USING btree (display_name);
CREATE UNIQUE INDEX "IssueStatus_pkey" ON public."IssueStatus" USING btree (id);
CREATE UNIQUE INDEX "Issue_pkey" ON public."Issue" USING btree (id);
CREATE UNIQUE INDEX "WorkDetail_pkey" ON public."WorkDetail" USING btree (id);
CREATE UNIQUE INDEX "WorkPackageStatus_pkey" ON public."WorkPackageStatus" USING btree (id);
CREATE UNIQUE INDEX "WorkPackage_pkey" ON public."WorkPackage" USING btree (id);

-- Add primary key constraints
ALTER TABLE "public"."Bid" ADD CONSTRAINT "Bid_pkey" PRIMARY KEY USING INDEX "Bid_pkey";
ALTER TABLE "public"."Issue" ADD CONSTRAINT "Issue_pkey" PRIMARY KEY USING INDEX "Issue_pkey";
ALTER TABLE "public"."IssueStatus" ADD CONSTRAINT "IssueStatus_pkey" PRIMARY KEY USING INDEX "IssueStatus_pkey";
ALTER TABLE "public"."WorkDetail" ADD CONSTRAINT "WorkDetail_pkey" PRIMARY KEY USING INDEX "WorkDetail_pkey";
ALTER TABLE "public"."WorkPackage" ADD CONSTRAINT "WorkPackage_pkey" PRIMARY KEY USING INDEX "WorkPackage_pkey";
ALTER TABLE "public"."WorkPackageStatus" ADD CONSTRAINT "WorkPackageStatus_pkey" PRIMARY KEY USING INDEX "WorkPackageStatus_pkey";

-- Add foreign key constraints
ALTER TABLE "public"."Bid" ADD CONSTRAINT "Bid_owner_fkey"
  FOREIGN KEY (owner) REFERENCES public.civic_os_users(id) NOT VALID;
ALTER TABLE "public"."Bid" VALIDATE CONSTRAINT "Bid_owner_fkey";

ALTER TABLE "public"."Bid" ADD CONSTRAINT "Bid_work_package_fkey"
  FOREIGN KEY (work_package) REFERENCES "WorkPackage"(id) NOT VALID;
ALTER TABLE "public"."Bid" VALIDATE CONSTRAINT "Bid_work_package_fkey";

ALTER TABLE "public"."Issue" ADD CONSTRAINT "Issue_created_user_fkey"
  FOREIGN KEY (created_user) REFERENCES public.civic_os_users(id) NOT VALID;
ALTER TABLE "public"."Issue" VALIDATE CONSTRAINT "Issue_created_user_fkey";

ALTER TABLE "public"."Issue" ADD CONSTRAINT "Issue_status_fkey"
  FOREIGN KEY (status) REFERENCES "IssueStatus"(id) NOT VALID;
ALTER TABLE "public"."Issue" VALIDATE CONSTRAINT "Issue_status_fkey";

ALTER TABLE "public"."Issue" ADD CONSTRAINT "Issue_work_package_fkey"
  FOREIGN KEY (work_package) REFERENCES "WorkPackage"(id) NOT VALID;
ALTER TABLE "public"."Issue" VALIDATE CONSTRAINT "Issue_work_package_fkey";

ALTER TABLE "public"."IssueStatus" ADD CONSTRAINT "IssueStatus_display_name_key"
  UNIQUE USING INDEX "IssueStatus_display_name_key";

ALTER TABLE "public"."WorkDetail" ADD CONSTRAINT "WorkDetail_added_by_fkey"
  FOREIGN KEY (added_by) REFERENCES public.civic_os_users(id) NOT VALID;
ALTER TABLE "public"."WorkDetail" VALIDATE CONSTRAINT "WorkDetail_added_by_fkey";

ALTER TABLE "public"."WorkDetail" ADD CONSTRAINT "WorkDetail_issue_fkey"
  FOREIGN KEY (issue) REFERENCES "Issue"(id) NOT VALID;
ALTER TABLE "public"."WorkDetail" VALIDATE CONSTRAINT "WorkDetail_issue_fkey";

ALTER TABLE "public"."WorkPackage" ADD CONSTRAINT "WorkPackage_status_fkey"
  FOREIGN KEY (status) REFERENCES "WorkPackageStatus"(id) NOT VALID;
ALTER TABLE "public"."WorkPackage" VALIDATE CONSTRAINT "WorkPackage_status_fkey";

-- Grant permissions
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "public"."Bid" TO web_anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "public"."Issue" TO web_anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "public"."IssueStatus" TO web_anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "public"."WorkDetail" TO web_anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "public"."WorkPackage" TO web_anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "public"."WorkPackageStatus" TO web_anon, authenticated;

-- Grant sequence permissions
GRANT USAGE ON SEQUENCE "public"."Bid_id_seq" TO web_anon, authenticated;
GRANT USAGE ON SEQUENCE "public"."Issue_id_seq" TO web_anon, authenticated;
GRANT USAGE ON SEQUENCE "public"."IssueStatus_id_seq" TO web_anon, authenticated;
GRANT USAGE ON SEQUENCE "public"."WorkDetail_id_seq" TO web_anon, authenticated;
GRANT USAGE ON SEQUENCE "public"."WorkPackage_id_seq" TO web_anon, authenticated;
GRANT USAGE ON SEQUENCE "public"."WorkPackageStatus_id_seq" TO web_anon, authenticated;

-- Enable Row Level Security
ALTER TABLE "public"."Bid" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."Issue" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."IssueStatus" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."WorkDetail" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."WorkPackage" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."WorkPackageStatus" ENABLE ROW LEVEL SECURITY;

-- RLS Policies for Bid
CREATE POLICY "Bid: read permission" ON "public"."Bid"
  FOR SELECT
  TO PUBLIC
  USING (public.has_permission('Bid', 'read'));

CREATE POLICY "Bid: create permission" ON "public"."Bid"
  FOR INSERT
  TO PUBLIC
  WITH CHECK (public.has_permission('Bid', 'create'));

CREATE POLICY "Bid: update permission" ON "public"."Bid"
  FOR UPDATE
  TO PUBLIC
  USING (public.has_permission('Bid', 'update'))
  WITH CHECK (public.has_permission('Bid', 'update'));

CREATE POLICY "Bid: delete permission" ON "public"."Bid"
  FOR DELETE
  TO PUBLIC
  USING (public.has_permission('Bid', 'delete'));

-- RLS Policies for Issue
CREATE POLICY "Issue: read permission" ON "public"."Issue"
  FOR SELECT
  TO PUBLIC
  USING (public.has_permission('Issue', 'read'));

CREATE POLICY "Issue: create permission" ON "public"."Issue"
  FOR INSERT
  TO PUBLIC
  WITH CHECK (public.has_permission('Issue', 'create'));

CREATE POLICY "Issue: update permission" ON "public"."Issue"
  FOR UPDATE
  TO PUBLIC
  USING (public.has_permission('Issue', 'update'))
  WITH CHECK (public.has_permission('Issue', 'update'));

CREATE POLICY "Issue: delete permission" ON "public"."Issue"
  FOR DELETE
  TO PUBLIC
  USING (public.has_permission('Issue', 'delete'));

-- RLS Policies for IssueStatus
CREATE POLICY "IssueStatus: read permission" ON "public"."IssueStatus"
  FOR SELECT
  TO PUBLIC
  USING (public.has_permission('IssueStatus', 'read'));

CREATE POLICY "IssueStatus: create permission" ON "public"."IssueStatus"
  FOR INSERT
  TO PUBLIC
  WITH CHECK (public.has_permission('IssueStatus', 'create'));

CREATE POLICY "IssueStatus: update permission" ON "public"."IssueStatus"
  FOR UPDATE
  TO PUBLIC
  USING (public.has_permission('IssueStatus', 'update'))
  WITH CHECK (public.has_permission('IssueStatus', 'update'));

CREATE POLICY "IssueStatus: delete permission" ON "public"."IssueStatus"
  FOR DELETE
  TO PUBLIC
  USING (public.has_permission('IssueStatus', 'delete'));

-- RLS Policies for WorkDetail
CREATE POLICY "WorkDetail: read permission" ON "public"."WorkDetail"
  FOR SELECT
  TO PUBLIC
  USING (public.has_permission('WorkDetail', 'read'));

CREATE POLICY "WorkDetail: create permission" ON "public"."WorkDetail"
  FOR INSERT
  TO PUBLIC
  WITH CHECK (public.has_permission('WorkDetail', 'create'));

CREATE POLICY "WorkDetail: update permission" ON "public"."WorkDetail"
  FOR UPDATE
  TO PUBLIC
  USING (public.has_permission('WorkDetail', 'update'))
  WITH CHECK (public.has_permission('WorkDetail', 'update'));

CREATE POLICY "WorkDetail: delete permission" ON "public"."WorkDetail"
  FOR DELETE
  TO PUBLIC
  USING (public.has_permission('WorkDetail', 'delete'));

-- RLS Policies for WorkPackage
CREATE POLICY "WorkPackage: read permission" ON "public"."WorkPackage"
  FOR SELECT
  TO PUBLIC
  USING (public.has_permission('WorkPackage', 'read'));

CREATE POLICY "WorkPackage: create permission" ON "public"."WorkPackage"
  FOR INSERT
  TO PUBLIC
  WITH CHECK (public.has_permission('WorkPackage', 'create'));

CREATE POLICY "WorkPackage: update permission" ON "public"."WorkPackage"
  FOR UPDATE
  TO PUBLIC
  USING (public.has_permission('WorkPackage', 'update'))
  WITH CHECK (public.has_permission('WorkPackage', 'update'));

CREATE POLICY "WorkPackage: delete permission" ON "public"."WorkPackage"
  FOR DELETE
  TO PUBLIC
  USING (public.has_permission('WorkPackage', 'delete'));

-- RLS Policies for WorkPackageStatus
CREATE POLICY "WorkPackageStatus: read permission" ON "public"."WorkPackageStatus"
  FOR SELECT
  TO PUBLIC
  USING (public.has_permission('WorkPackageStatus', 'read'));

CREATE POLICY "WorkPackageStatus: create permission" ON "public"."WorkPackageStatus"
  FOR INSERT
  TO PUBLIC
  WITH CHECK (public.has_permission('WorkPackageStatus', 'create'));

CREATE POLICY "WorkPackageStatus: update permission" ON "public"."WorkPackageStatus"
  FOR UPDATE
  TO PUBLIC
  USING (public.has_permission('WorkPackageStatus', 'update'))
  WITH CHECK (public.has_permission('WorkPackageStatus', 'update'));

CREATE POLICY "WorkPackageStatus: delete permission" ON "public"."WorkPackageStatus"
  FOR DELETE
  TO PUBLIC
  USING (public.has_permission('WorkPackageStatus', 'delete'));

-- Apply timestamp triggers
CREATE TRIGGER set_created_at_trigger
  BEFORE INSERT ON public."Bid"
  FOR EACH ROW
  EXECUTE FUNCTION public.set_created_at();

CREATE TRIGGER set_created_at_trigger
  BEFORE INSERT ON public."Issue"
  FOR EACH ROW
  EXECUTE FUNCTION public.set_created_at();

CREATE TRIGGER set_updated_at_trigger
  BEFORE INSERT OR UPDATE ON public."Issue"
  FOR EACH ROW
  EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER set_created_at_trigger
  BEFORE INSERT ON public."IssueStatus"
  FOR EACH ROW
  EXECUTE FUNCTION public.set_created_at();

CREATE TRIGGER set_created_at_trigger
  BEFORE INSERT ON public."WorkDetail"
  FOR EACH ROW
  EXECUTE FUNCTION public.set_created_at();

CREATE TRIGGER set_created_at_trigger
  BEFORE INSERT ON public."WorkPackage"
  FOR EACH ROW
  EXECUTE FUNCTION public.set_created_at();

CREATE TRIGGER set_updated_at_trigger
  BEFORE INSERT OR UPDATE ON public."WorkPackage"
  FOR EACH ROW
  EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER set_created_at_trigger
  BEFORE INSERT ON public."WorkPackageStatus"
  FOR EACH ROW
  EXECUTE FUNCTION public.set_created_at();

-- Notify PostgREST to reload schema cache
NOTIFY pgrst, 'reload schema';
